---
title: "Change in blood chemistry values over time in Lassa fever patients"
---

```{r}
library(Rmisc)
```

```{r}
filename = "C:/Users/kelse/Documents/Year_2/Rotations/Colubri/Lassa_virus/practice_data/commcare-randomized-data-2018-2020.csv"

lassa <- read.csv(filename, header = TRUE, sep = ",")
```


```{r}
upper <- function(x) {
  CI(na.omit(x))["upper"]
}

lower <- function(x) {
  CI(na.omit(x))["lower"]
}
```

```{r}
albumin_avg <- lassa %>%
  filter(clinical_outcome.outcome == "died" | clinical_outcome.outcome == "recovered") %>%
  group_by(clinical_outcome.outcome) %>%
  dplyr::summarise(across(starts_with("blood_chemistry_list.albumin"), ~ mean(.x, na.rm = TRUE)))

albumin_lower <- lassa %>%
  filter(clinical_outcome.outcome == "died" | clinical_outcome.outcome == "recovered") %>%
  group_by(clinical_outcome.outcome) %>%
  dplyr::summarise(across(starts_with("blood_chemistry_list.albumin"), ~ lower(.x)))

albumin_upper <- lassa %>%
  filter(clinical_outcome.outcome == "died" | clinical_outcome.outcome == "recovered") %>%
  group_by(clinical_outcome.outcome) %>%
  dplyr::summarise(across(starts_with("blood_chemistry_list.albumin"), ~ upper(.x)))

alb_lower <- albumin_lower %>%
  pivot_longer(cols = 2:21, names_to = "day")

alb_avg <- albumin_avg %>%
  pivot_longer(cols = 2:21, names_to = "day")

alb_upper <- albumin_upper %>%
  pivot_longer(cols = 2:21, names_to = "day")
```


```{r}
alb_CI <- data.frame(cbind("outcome" = alb_avg$clinical_outcome.outcome, "day" = alb_avg$day, "mean" = alb_avg$value, "lower" = alb_lower$value, "upper" = alb_upper$value))
#subset rows that don't have missing data 
alb_CI <- alb_CI[c(1:5, 21:25),]
```

```{r}
ggplot(alb_CI, aes(x=day, y=mean, group=outcome)) +
  geom_line(aes(color=outcome)) +
  geom_point() + 
  geom_ribbon(aes(ymin=lower, ymax=upper, group = outcome), linetype=2, alpha=0.1) + 
  scale_x_discrete(labels=c("0", "1", "2", "3", "4")) + 
  ggtitle("Average albumin of LF patients during hospital stay")
```

Need to change y axis from discrete to continuous so I can format the axis 
