Load packages.
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

Load data.
```{r}
filename = "C:/Users/kelse/Documents/Year_2/Rotations/Colubri/Lassa_virus/practice_data/commcare-randomized-data-2018-2020_2.csv"

lassa <- read.csv(filename, header = TRUE, sep = ",")

lassa <- lassa %>%
  filter(lassa$clinical_outcome.outcome == "recovered" | lassa$clinical_outcome.outcome == "died")
```

Create variables and subset data.
```{r}
#create age and ID variables
lassa$ID <- seq.int(nrow(lassa))
age <- as.numeric(lassa$basic_information.age)

#reformat outcome variable to 0 and 1
outcome <- lassa %>%
  select(clinical_outcome.outcome)

outcome <- ifelse(outcome == "recovered", 0, 1)
```

Choose either creatinine or white cell count as test case - *CHOOSE 1.*
```{r}
######## subset white cell count longitudinal data
#val <- lassa %>%
 # select(contains("hematology_list.white_cell_count"))

#days <- lassa %>%
  #select(contains("hematology_list.days_since_admission")) 


######## subset creatinine data
val <- lassa %>%
  select(starts_with("blood_chemistry")) %>%
  select(contains("creatinine"))

days <- lassa %>%
  select(contains("blood_chemistry_list.days_since_admission")) 
```

Format variables and dataframe.
```{r}
day0 = data.frame(cbind("ID" = lassa$ID, "outcome" = outcome, "age" = age, "day" = days[,1], "val" = val[,1]))
day1 = data.frame(cbind("ID" = lassa$ID, "outcome" = outcome, "age" = age, "day" = days[,2], "val" = val[,2]))
day2 = data.frame(cbind("ID" = lassa$ID, "outcome" = outcome, "age" = age, "day" = days[,3], "val" = val[,3]))
day3 = data.frame(cbind("ID" = lassa$ID, "outcome" = outcome, "age" = age, "day" = days[,4], "val" = val[,4]))
day4 = data.frame(cbind("ID" = lassa$ID, "outcome" = outcome, "age" = age, "day" = days[,5], "val" = val[,5]))
day5 = data.frame(cbind("ID" = lassa$ID, "outcome" = outcome, "age" = age, "day" = days[,6], "val" = val[,6]))
day6 = data.frame(cbind("ID" = lassa$ID, "outcome" = outcome, "age" = age, "day" = days[,7], "val" = val[,7]))

#format variables and rearrange columns
long_data <- rbind(day0, day1, day2, day3, day4, day5, day6)

long_data$ID <- as.numeric(as.character(long_data$ID))
long_data$outcome <- as.factor(long_data$clinical_outcome.outcome)

#format day variable
long_data$day <- gsub(" days", "",  long_data$day)
long_data$day <- as.numeric(long_data$day)

#arrange data by ID
long_data <- arrange(long_data[c(1,6,4,5,3)], ID)
long_data$ID <- as.factor(long_data$ID)
long_data_raw <- long_data

#only keep complete cases and remove duplicates
long_data <- distinct(long_data) #remove duplicates
long_data <- long_data[complete.cases(long_data), ] #keep complete cases
```

Visually inspect data.
```{r}
head(long_data, 10)
```


Print number of tests associated with each ID.
```{r}
z <- data.frame(table(long_data$ID))
table(z$Freq)
```

Subset data to include only patients that have 2 or more tests.

```{r}
newdata <-long_data %>% 
  group_by(ID) %>% 
  filter(n()==2 | n() == 3)
newdata
```

Graph the results

```{r}
# Plot the longitudinal profiles for the  selected patients
ggplot(data = newdata, aes(x = day, y = val, group = ID, colour = outcome)) +
  geom_line(aes(color = as.factor(outcome), linetype = as.factor(outcome)), size = 0.7) +
  scale_linetype_manual(values = c("longdash", "solid")) + 
  scale_color_manual(values = c("black", "red")) + theme_bw() +
  theme(legend.position = "", panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
  labs(x = "day", y = "Creatinine", colour = "outcome ")
```


```{r}
library(dplyr)

```

