---
title: "Mortality as a function of age in Lassa fever patients"
---

```{r}
library(data.table)
library(stringr)
library(dplyr)
library(ggplot2)
library(dplyr)
```


```{r}
filename = "C:/Users/kelse/Documents/Year_2/Rotations/Colubri/Lassa_virus/practice_data/commcare-randomized-data-2018-2020.csv"

lassa <- read.csv(filename, header = TRUE, sep = ",")
```

```{r}
lassa %>%
  group_by(clinical_outcome.outcome) %>%
  summarize(basic_information.age)

agebreaks <- c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)
agelabels <- c("0-10", "10-20", "20-30", "30-40", "40-50", "50-60", "60-70", "70-80", "80-90")

ageGroups <- setDT(lassa)[ , agegroups := cut(basic_information.age, 
                                breaks = agebreaks, 
                                right = FALSE, 
                                labels = agelabels)]
ageTotal <- ageGroups %>%
  count(agegroups)

ageSum <- ageGroups %>%
  filter(str_detect(clinical_outcome.outcome, "recovered")) %>%
  count(agegroups)

names(ageSum) <- c("agegroups", "live")

age <- merge(ageTotal, ageSum)
age$die <- age$n - age$live
age$cfr <- round((age$die / age$n * 100),1)
age$string <- paste(age$cfr,"%"," (",age$die,"/",age$n,")", sep="")
age <- age[-1,]
```

```{r}
p <- ggplot(age, aes(x=agegroups, y=cfr)) +
  geom_bar(stat="identity", color = "darkred", fill="darkred") +
  geom_text(aes(label=string), vjust=-0.3, size=3.5) +
  xlab("Age group (years)") + 
  ylab("Case fatality rate (%)") +
  ggtitle("Mortality as a function of age in Lassa fever patients") +
  theme_minimal()

p + geom_line(aes(x = agegroups, y = n), color = 'black', group = 1) 
```


