
```{r}
char_to_num <- function(data) {
mgsub(data, c("D14+ D14 D13 D12 D11 D10 D9 D8 D7 D6 D5 D4 D3 D2 D1", "D14 D13 D12 D11 D10 D9 D8 D7 D6 D5 D4 D3 D2 D1",  "D13 D12 D11 D10 D9 D8 D7 D6 D5 D4 D3 D2 D1", "D12 D11 D10 D9 D8 D7 D6 D5 D4 D3 D2 D1", "D11 D10 D9 D8 D7 D6 D5 D4 D3 D2 D1", "D10 D9 D8 D7 D6 D5 D4 D3 D2 D1", "D9 D8 D7 D6 D5 D4 D3 D2 D1", "D8 D7 D6 D5 D4 D3 D2 D1", "D7 D6 D5 D4 D3 D2 D1", "D6 D5 D4 D3 D2 D1", "D5 D4 D3 D2 D1", "D4 D3 D2 D1", "D3 D2 D1", "D2 D1", "D1"), 
      c(">14", 14:1))
}

feat <- lassa %>%
  select(contains("clinical_features")) %>%
  select(!contains("vital")) %>% #remove continuous variables 
  select(!contains("clinical_factors.additional_clinical_features")) %>%
  select(contains("duration"))

names(feat) <- mgsub(names(feat), c("clinical_features.before_admission_group.before_admission",
                     "_symptom_duration.",
                     "_bleeding_question_group.bleeding_duration.", 
                     "_duration.symptom",
                     "_before_admission",
                     "_duration.days_symptom"),
      c("", "", "", "", "", "_days"))
feat[feat == ""] <- 0
```

```{r}
feat$fever
days <- feat %>%
  select(contains("days")) 
names(days) <- mgsub(names(days), c("_days"), c(""))
days <- map_df(days, as.numeric)


duration <- feat %>%
  select(!contains("days"))
duration <- data.frame(map(duration, char_to_num))


as.numeric(duration$fever)

d <- duration %>%
  mutate(fever = as.numeric(fever))

library(dplyr)
duration %>% 
  mutate(across(everything(), ~ 
       coalesce(na_if(days[[cur_column()]], ">14"), .)))

sum(is.na(as.numeric(duration$fever)))

data.frame(table(duration$fever))
```

```{r}

values <- data.frame(A = c("banana", "orange", "apple", "pear", "+"),
                 B = c("apple", "+", "banana", "melon", "orange"))

others <- data.frame(A = c("", "", "", "", "apple"),
                     B = c("", "pear", "", "", ""))

names <- c("A", "B")

#function to replace values of "+" with corresponding value in other data.frame
replace_with_other <- function(x, y) {
  ifelse(x == ">14", y, x)
}

Map(replace_with_other, duration[names], days[names])

duration

days

names <- names(days)

duration == ">14"

duration$fever == ">14"
```

Sometimes when response is >14, there is no corresponding value describing how many days patient experienced symptom. How should I code these? Do they become NA?
