
Calculate average number of days patients experienced the most frequently reported symptoms before admission.

```{r}
library(ggpubr)
library(rstatix)
library(dplyr)
library(textclean)
library(tidyr)
library(stringr)
library(purrr)
```

Load data.

```{r}
filename = "C:/Users/kelse/Documents/Year_2/Rotations/Colubri/Lassa_virus/practice_data/commcare-randomized-data-2018-2020.csv"

lassa <- read.csv(filename, header = TRUE, sep = ",")
```

```{r}
#subset data
feat <- lassa %>%
  select(contains("clinical_features")) %>%
  select(!contains("vital")) %>% #remove continuous variables 
  select(!contains("clinical_factors.additional_clinical_features")) %>%
  select(contains("duration")) %>%
  select(!contains("days"))

#remove redundant text from names
names(feat) <- mgsub(names(feat), c("clinical_features.before_admission_group.before_admission",
                     "_symptom_duration.",
                     "_bleeding_question_group.bleeding_duration.", 
                     "_duration.symptom",
                     "_before_admission",
                     "_duration.days_symptom"),
      c("", "", "", "", "", "_days"))

#count number of times D appears in each string to convert string to a number
feat[] <- lapply(feat, function(x) str_count(x, "D"))
```

Calculate column means for each symptom. Do not include values of 0, because we want mean number of days patient experienced symptom, only if the patient reported the symptom.

```{r}
#replace values of 0 with NA
is.na(feat) <- feat==0

#calculate column means
Sx_means <- sort(colMeans(feat, na.rm=TRUE))

#add outcome to data frame
duration_df <- cbind("outcome" = lassa$clinical_outcome.outcome, feat)

#create cutoff variable equal to 90% of total number of observations
cutoff <-  nrow(lassa)*.9

#only include variables where at least 10% of patients reported symptoms
varnames <- names(Filter(function(x) x < cutoff, colSums(is.na(feat))))
```

Create ggplot and add significance.

```{r}
# calculate p values
df <- duration_df %>%
  filter(outcome == "recovered" | outcome == "died")

df <- df[,colSums(is.na(df))<(nrow(df)*.9)] # remove columns where > 90% of values are equal to NA

p_val <- map(df[-1], function(x) t.test(x ~ df$outcome)["p.value"])

p_val <- data.frame(unlist(p_val))

rownames(p_val) <- gsub(".p.value","", rownames(p_val))

p_val$symptom <- rownames(p_val)
```

```{r}
# get data ready for gg plot
duration_summary <- duration_df %>%
  pivot_longer(cols = varnames, names_to = 'symptom') %>% 
  filter(outcome == "died" | outcome == "recovered") %>%
  group_by(outcome, symptom) %>%
  dplyr::summarise(mean = mean(value, na.rm = TRUE), sd = sd(value, na.rm = TRUE), .groups = 'drop')

#create ggplot
p <- ggplot(data = duration_summary, mapping = aes(x = symptom, y = mean, fill = outcome)) + 
  geom_bar(stat="identity", position=position_dodge()) + 
  ggtitle("Average number of days patients experienced symptom before admission") +
  ylab("Days") +  
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p
# save plot to pdf
pdf("./lassa_fever_analysis/avg_days_symptom_before_admission.pdf")
p
dev.off()

```

Save table output to csv.

```{r}
data <- duration_summary %>%
  pivot_wider(names_from = outcome, values_from = c(mean, sd))
data
data <- merge(data, p_val , by= "symptom")
dir.create("lassa_fever_analysis")
write.csv(data, "./lassa_fever_analysis/avg_days_of_symptom_before_admission.csv")
```

